[package]
name = "mcscs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Arama"]
description = "MCSCS powered by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
indicatif = "0.17"
rayon = "1.8"
regex = "1.10"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
tokio = { version = "1.36", features = ["full"] }
