[package]
name = "mcscs"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
authors = ["Arama"]
description = "MCSCS powered by Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies] # abcdefghijklmnopqrstuvwxyz
chrono = "0.4"
hex = "0.4"
indicatif = "0.17"
lazy_static = "1.4"
log = "0.4"
log4rs = "1.3"
rayon = "1.8"
regex = "1.10"
reqwest = { version = "0.11", features = ["json"] }
serde_json = "1"
tokio = { version = "1.36", features = ["full"] }
sha1 = "0.10"
